export const PUPIL_BEHAVIOR = {
    DREAMER: {
        ignorance: { minPoints: 3, maxPoints: 6 },
        boredom: { minPoints: 2, maxPoints: 6 },
        skills: {},
        uniqueSkills: {},
        petSkill: {},
        weight: 1,
    },
    JOVIAL: {
        ignorance: { minPoints: 2, maxPoints: 4 },
        boredom: { minPoints: 2, maxPoints: 3 },
        skills: {},
        uniqueSkills: {},
        petSkill: {},
        weight: 1,
    },
    CLEVER: {
        ignorance: { minPoints: 2, maxPoints: 4 },
        boredom: { minPoints: 2, maxPoints: 3 },
        skills: {},
        uniqueSkills: {},
        petSkill: {},
        weight: 1,
    },
    SHY: {
        ignorance: { minPoints: 2, maxPoints: 4 },
        boredom: { minPoints: 2, maxPoints: 3 },
        skills: {},
        uniqueSkills: {},
        petSkill: {},
        weight: 1,
    },
    CLOWN: {
        ignorance: { minPoints: 2, maxPoints: 4 },
        boredom: { minPoints: 1, maxPoints: 4 },
        skills: {},
        uniqueSkills: {},
        petSkill: {},
        weight: 1,
    },
    NOISY: {
        ignorance: { minPoints: 3, maxPoints: 4 },
        boredom: { minPoints: 1, maxPoints: 4 },
        skills: {},
        uniqueSkills: {},
        petSkill: {},
        weight: 1,
    },
    MANIPULATOR: {
        ignorance: { minPoints: 2, maxPoints: 4 },
        boredom: { minPoints: 0, maxPoints: 3 },
        skills: {},
        uniqueSkills: {},
        petSkill: {},
        weight: 1,
    },
    HYPERACTIVE: {
        ignorance: { minPoints: 3, maxPoints: 5 },
        boredom: { minPoints: 1, maxPoints: 4 },
        skills: {},
        uniqueSkills: {},
        petSkill: {},
        weight: 5,
    },
} as const;

export type PupilBehavior = keyof typeof PUPIL_BEHAVIOR;